PRAGMA foreign_keys = ON;

create table category (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name VARCHAR(30),
    category_desc TEXT,
    category_status boolean
);

insert into category (category_name, category_desc, category_status) values ('Elderly Companionship', 'Visit and provide social interaction to isolated seniors in homes or care facilities', false);
insert into category (category_name, category_desc, category_status) values ('Meal Delivery', 'Deliver hot meals to homebound elderly, disabled, or ill individuals', false);
insert into category (category_name, category_desc, category_status) values ('Pet Care Support', 'Help individuals care for pets through feeding, walking, or veterinary assistance', true);
insert into category (category_name, category_desc, category_status) values ('Park Restoration', 'Clean and maintain local parks through litter removal and planting activities', true);
insert into category (category_name, category_desc, category_status) values ('Shelter Assistance', 'Support homeless shelters by serving meals, organizing donations, or providing companionship', false);
insert into category (category_name, category_desc, category_status) values ('Emergency Relief', 'Assist communities during natural disasters through cleanup and supply distribution', true);
insert into category (category_name, category_desc, category_status) values ('Event Coordination', 'Plan and organize neighborhood gatherings and community celebrations', false);
insert into category (category_name, category_desc, category_status) values ('Wellness Checkups', 'Assist with health screening events and provide basic health education', true);
insert into category (category_name, category_desc, category_status) values ('Tutoring Services', 'Provide academic support to students in reading, math, or other subjects', false);
insert into category (category_name, category_desc, category_status) values ('Cultural Activities', 'Lead arts, crafts, or cultural workshops for underserved communities', false);
insert into category (category_name, category_desc, category_status) values ('Fitness Programs', 'Organize sports and recreational activities for underserved youth', false);
insert into category (category_name, category_desc, category_status) values ('Food Distribution', 'Sort, pack, and distribute food at food banks for families in need', true);
insert into category (category_name, category_desc, category_status) values ('Counseling Support', 'Provide emotional support and resource connections for mental health needs', true);
insert into category (category_name, category_desc, category_status) values ('Military Family Aid', 'Support veteran families with childcare, errands, or home maintenance', false);
insert into category (category_name, category_desc, category_status) values ('Leadership Workshops', 'Empower women through skill-building in leadership and entrepreneurship', false);
insert into category (category_name, category_desc, category_status) values ('Newcomer Services', 'Help refugees settle through language practice and resource navigation', false);
insert into category (category_name, category_desc, category_status) values ('24/7 Phone Support', 'Staff crisis hotlines to provide immediate support during emergencies', true);
insert into category (category_name, category_desc, category_status) values ('Reading Assistance', 'Teach basic literacy and reading skills to adults', true);
insert into category (category_name, category_desc, category_status) values ('Housing Navigation', 'Guide families through the process of finding affordable housing', false);
insert into category (category_name, category_desc, category_status) values ('Legal Consultation', 'Offer pro bono legal guidance on housing, immigration, or family law', false);
insert into category (category_name, category_desc, category_status) values ('Digital Skills', 'Teach computer basics and internet navigation to seniors and low-income individuals', false);
insert into category (category_name, category_desc, category_status) values ('Career Mentoring', 'Guide at-risk youth in career exploration and job readiness skills', false);
insert into category (category_name, category_desc, category_status) values ('Urban Gardening', 'Build community gardens providing fresh produce to food-insecure neighborhoods', false);
insert into category (category_name, category_desc, category_status) values ('Reentry Programs', 'Support formerly incarcerated individuals with job training and housing', false);
insert into category (category_name, category_desc, category_status) values ('Addiction Support', 'Facilitate recovery groups and connect individuals to treatment resources', false);
insert into category (category_name, category_desc, category_status) values ('Skills Training', 'Teach vocational skills like carpentry, coding, or culinary arts', false);
insert into category (category_name, category_desc, category_status) values ('Accessibility Support', 'Assist people with disabilities with daily tasks and transportation', true);
insert into category (category_name, category_desc, category_status) values ('Health Outreach', 'Distribute health information about vaccinations and preventive care', false);
insert into category (category_name, category_desc, category_status) values ('Rights Education', 'Teach community members about their civil and tenant rights', false);
insert into category (category_name, category_desc, category_status) values ('Language Exchange', 'Connect native speakers with newcomers for language practice and friendship', true);
insert into category (category_name, category_desc, category_status) values ('Senior Recreation', 'Lead activities, games, and exercise classes at senior centers', true);
insert into category (category_name, category_desc, category_status) values ('Safety Partnerships', 'Build trust between police and community through dialogue programs', false);
insert into category (category_name, category_desc, category_status) values ('Abuse Prevention', 'Educate about domestic violence warning signs and support resources', false);
insert into category (category_name, category_desc, category_status) values ('Immigration Help', 'Assist immigrants with paperwork, translation, and citizenship preparation', false);
insert into category (category_name, category_desc, category_status) values ('Animal Rescue', 'Care for injured or orphaned wildlife through rehabilitation', false);
insert into category (category_name, category_desc, category_status) values ('Healing Through Music', 'Lead therapeutic music sessions for hospital patients or hospice residents', false);
insert into category (category_name, category_desc, category_status) values ('Home Maintenance', 'Provide free home repairs and safety modifications for elderly homeowners', true);
insert into category (category_name, category_desc, category_status) values ('Transit Advocacy', 'Campaign for improved public transportation access in underserved areas', true);
insert into category (category_name, category_desc, category_status) values ('Neighborhood Cleanup', 'Remove litter and beautify streets, parks, and public spaces', true);
insert into category (category_name, category_desc, category_status) values ('Money Management', 'Teach budgeting, saving, and financial planning to low-income families', false);
insert into category (category_name, category_desc, category_status) values ('Teen Leadership', 'Develop leadership skills and civic engagement in young people', true);
insert into category (category_name, category_desc, category_status) values ('Creative Healing', 'Use art as therapeutic tool for trauma recovery and emotional expression', true);
insert into category (category_name, category_desc, category_status) values ('LGBTQ+ Outreach', 'Provide safe spaces, peer support, and advocacy for LGBTQ+ individuals', false);
insert into category (category_name, category_desc, category_status) values ('Media Production', 'Create community radio content highlighting local stories and issues', false);
insert into category (category_name, category_desc, category_status) values ('Solar Installation', 'Install solar panels for low-income homes to reduce utility costs', true);
insert into category (category_name, category_desc, category_status) values ('Performance Arts', 'Direct community theater productions showcasing local talent', true);
insert into category (category_name, category_desc, category_status) values ('Surplus Food Recovery', 'Collect excess food from restaurants to redistribute to families', false);
insert into category (category_name, category_desc, category_status) values ('Policy Research', 'Research community issues to inform advocacy and policy solutions', false);
insert into category (category_name, category_desc, category_status) values ('Voter Registration', 'Register community members and provide voter education', true);
insert into category (category_name, category_desc, category_status) values ('Heritage Conservation', 'Restore historic buildings and landmarks important to community identity', true);
insert into category (category_name, category_desc, category_status) values ('Youth Athletics', 'Coach underserved children in sports while teaching teamwork and discipline', false);
insert into category (category_name, category_desc, category_status) values ('Singing Group', 'Lead community choir practices and performances', true);
insert into category (category_name, category_desc, category_status) values ('Science Education', 'Teach STEM through hands-on experiments to underserved students', false);
insert into category (category_name, category_desc, category_status) values ('Cooperative Farming', 'Maintain community farm plots where neighbors grow produce together', false);
insert into category (category_name, category_desc, category_status) values ('Business Development', 'Help aspiring entrepreneurs start small businesses through mentoring', true);
insert into category (category_name, category_desc, category_status) values ('Prison Literacy', 'Teach reading and GED preparation to incarcerated individuals', false);
insert into category (category_name, category_desc, category_status) values ('Parenting Support', 'Guide first-time parents through infant care and child development', true);
insert into category (category_name, category_desc, category_status) values ('Mobile Library', 'Bring books and reading programs to underserved neighborhoods', true);
insert into category (category_name, category_desc, category_status) values ('Youth Leadership', 'Train teenagers to plan and lead community service projects', false);
insert into category (category_name, category_desc, category_status) values ('Mural Creation', 'Paint public murals collaboratively to beautify neighborhoods', true);
insert into category (category_name, category_desc, category_status) values ('Bike Maintenance', 'Repair bicycles for low-income commuters who depend on bikes', true);
insert into category (category_name, category_desc, category_status) values ('Classical Music', 'Perform free concerts for seniors in care facilities', false);
insert into category (category_name, category_desc, category_status) values ('Dance Instruction', 'Teach various dance styles to all ages as exercise and expression', false);
insert into category (category_name, category_desc, category_status) values ('Yoga Outreach', 'Lead free yoga classes for stressed populations like caregivers or veterans', false);
insert into category (category_name, category_desc, category_status) values ('Culinary Training', 'Teach cooking and nutrition to food-insecure families', true);
insert into category (category_name, category_desc, category_status) values ('Photography Lessons', 'Teach photography skills to youth as creative outlet', true);
insert into category (category_name, category_desc, category_status) values ('Cinema Club', 'Screen documentaries with discussions on social issues', false);
insert into category (category_name, category_desc, category_status) values ('Reading Circle', 'Facilitate book club discussions promoting literacy and connection', false);
insert into category (category_name, category_desc, category_status) values ('Acting Workshop', 'Teach drama to shy youth to build confidence', true);
insert into category (category_name, category_desc, category_status) values ('Vocal Training', 'Teach singing techniques through lessons and workshops', false);
insert into category (category_name, category_desc, category_status) values ('Brass Ensemble', 'Lead community band rehearsals and performances', false);
insert into category (category_name, category_desc, category_status) values ('Dance Performances', 'Choreograph community dance shows celebrating cultural traditions', false);
insert into category (category_name, category_desc, category_status) values ('Exhibition Space', 'Curate art exhibitions showcasing local artists', false);
insert into category (category_name, category_desc, category_status) values ('Craft Workshops', 'Teach handmade crafts as therapeutic and income-generating skills', true);
insert into category (category_name, category_desc, category_status) values ('Garden Cooperative', 'Grow vegetables collaboratively in shared community plots', false);
insert into category (category_name, category_desc, category_status) values ('Running Groups', 'Lead community running clubs and organize charity races', true);
insert into category (category_name, category_desc, category_status) values ('Cycling Tours', 'Organize group bike rides promoting eco-friendly transportation', false);
insert into category (category_name, category_desc, category_status) values ('Nature Walks', 'Lead hiking groups for fitness and nature appreciation', false);
insert into category (category_name, category_desc, category_status) values ('Bird Watching', 'Teach nature observation and bird identification skills', true);
insert into category (category_name, category_desc, category_status) values ('Angling Programs', 'Teach fishing and water safety to youth', true);
insert into category (category_name, category_desc, category_status) values ('Fiber Arts', 'Teach knitting to create items donated to shelters and hospitals', true);
insert into category (category_name, category_desc, category_status) values ('Tailoring Classes', 'Teach sewing and clothing repair for sustainability', false);
insert into category (category_name, category_desc, category_status) values ('Ceramics Studio', 'Teach pottery to beginners as creative expression', true);
insert into category (category_name, category_desc, category_status) values ('Wood Craft', 'Teach safe woodworking for building furniture and toys', false);
insert into category (category_name, category_desc, category_status) values ('Strategy Games', 'Teach chess to youth to develop critical thinking', true);
insert into category (category_name, category_desc, category_status) values ('Tabletop Gaming', 'Host board game nights for social connection', false);
insert into category (category_name, category_desc, category_status) values ('Esports Programs', 'Run gaming tournaments for teens to develop teamwork', true);
insert into category (category_name, category_desc, category_status) values ('Card Games', 'Teach card games to seniors for cognitive function', false);
insert into category (category_name, category_desc, category_status) values ('Puzzle Solving', 'Host puzzle competitions and collaborative events', true);
insert into category (category_name, category_desc, category_status) values ('Paper Folding', 'Teach origami as meditative art promoting focus', true);
insert into category (category_name, category_desc, category_status) values ('Memory Albums', 'Help seniors create scrapbooks documenting life stories', false);
insert into category (category_name, category_desc, category_status) values ('Beautiful Writing', 'Teach calligraphy as therapeutic art and marketable skill', false);
insert into category (category_name, category_desc, category_status) values ('Painting Classes', 'Teach painting techniques to all skill levels', false);
insert into category (category_name, category_desc, category_status) values ('Sketching Workshops', 'Teach drawing fundamentals including perspective and shading', false);
insert into category (category_name, category_desc, category_status) values ('After-School Programs', 'Supervise and lead educational activities for youth', true);
insert into category (category_name, category_desc, category_status) values ('Elder Care', 'Assist seniors with grocery shopping, housekeeping, and companionship', true);
insert into category (category_name, category_desc, category_status) values ('Animal Adoption', 'Match rescued pets with loving homes through adoption events', false);
insert into category (category_name, category_desc, category_status) values ('Eco Conservation', 'Protect local ecosystems through habitat restoration', false);
insert into category (category_name, category_desc, category_status) values ('Street Outreach', 'Connect homeless individuals to shelter and social services', true);
insert into category (category_name, category_desc, category_status) values ('Crisis Response', 'Respond to emergencies by coordinating volunteers and supplies', false);