PRAGMA foreign_keys = ON;

create table category (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name VARCHAR(30),
    category_desc TEXT
);

insert into category (category_name, category_desc) values ('Elderly Companionship', 'Provide social interaction to isolated seniors');
insert into category (category_name, category_desc) values ('Meal Delivery', 'Deliver meals to homebound individuals');
insert into category (category_name, category_desc) values ('Pet Care Support', 'Help with pet feeding, walking, and care');
insert into category (category_name, category_desc) values ('Park Restoration', 'Clean and maintain local parks');
insert into category (category_name, category_desc) values ('Shelter Assistance', 'Support homeless shelters with meals and donations');
insert into category (category_name, category_desc) values ('Emergency Relief', 'Assist communities during natural disasters');
insert into category (category_name, category_desc) values ('Event Coordination', 'Organize neighborhood gatherings');
insert into category (category_name, category_desc) values ('Wellness Checkups', 'Assist with health screening events');
insert into category (category_name, category_desc) values ('Tutoring Services', 'Provide academic support to students');
insert into category (category_name, category_desc) values ('Cultural Activities', 'Lead arts and cultural workshops');
insert into category (category_name, category_desc) values ('Fitness Programs', 'Organize sports activities for youth');
insert into category (category_name, category_desc) values ('Food Distribution', 'Sort and distribute food at food banks');
insert into category (category_name, category_desc) values ('Counseling Support', 'Provide emotional support connections');
insert into category (category_name, category_desc) values ('Military Family Aid', 'Support veteran families with daily tasks');
insert into category (category_name, category_desc) values ('Leadership Workshops', 'Empower through leadership training');
insert into category (category_name, category_desc) values ('Newcomer Services', 'Help refugees with language and resources');
insert into category (category_name, category_desc) values ('24/7 Phone Support', 'Staff crisis hotlines for emergencies');
insert into category (category_name, category_desc) values ('Reading Assistance', 'Teach literacy skills to adults');
insert into category (category_name, category_desc) values ('Housing Navigation', 'Guide families to affordable housing');
insert into category (category_name, category_desc) values ('Legal Consultation', 'Offer pro bono legal guidance');
insert into category (category_name, category_desc) values ('Digital Skills', 'Teach computer basics and internet use');
insert into category (category_name, category_desc) values ('Career Mentoring', 'Guide youth in career exploration');
insert into category (category_name, category_desc) values ('Urban Gardening', 'Build community gardens for fresh produce');
insert into category (category_name, category_desc) values ('Reentry Programs', 'Support formerly incarcerated with job training');
insert into category (category_name, category_desc) values ('Addiction Support', 'Facilitate recovery groups and resources');
insert into category (category_name, category_desc) values ('Skills Training', 'Teach vocational skills like carpentry or coding');
insert into category (category_name, category_desc) values ('Accessibility Support', 'Assist people with disabilities');
insert into category (category_name, category_desc) values ('Health Outreach', 'Distribute vaccination and health information');
insert into category (category_name, category_desc) values ('Rights Education', 'Teach about civil and tenant rights');
insert into category (category_name, category_desc) values ('Language Exchange', 'Connect speakers for language practice');
insert into category (category_name, category_desc) values ('Senior Recreation', 'Lead activities at senior centers');
insert into category (category_name, category_desc) values ('Safety Partnerships', 'Build trust between police and community');
insert into category (category_name, category_desc) values ('Abuse Prevention', 'Educate about domestic violence resources');
insert into category (category_name, category_desc) values ('Immigration Help', 'Assist with paperwork and citizenship prep');
insert into category (category_name, category_desc) values ('Animal Rescue', 'Care for injured wildlife');
insert into category (category_name, category_desc) values ('Healing Through Music', 'Lead therapeutic music sessions');
insert into category (category_name, category_desc) values ('Home Maintenance', 'Provide home repairs for elderly homeowners');
insert into category (category_name, category_desc) values ('Transit Advocacy', 'Campaign for improved public transportation');
insert into category (category_name, category_desc) values ('Neighborhood Cleanup', 'Remove litter and beautify public spaces');
insert into category (category_name, category_desc) values ('Money Management', 'Teach budgeting and financial planning');
insert into category (category_name, category_desc) values ('Teen Leadership', 'Develop leadership in young people');
insert into category (category_name, category_desc) values ('Creative Healing', 'Use art for trauma recovery');
insert into category (category_name, category_desc) values ('LGBTQ+ Outreach', 'Provide safe spaces and advocacy');
insert into category (category_name, category_desc) values ('Media Production', 'Create community radio content');
insert into category (category_name, category_desc) values ('Solar Installation', 'Install solar panels for low-income homes');
insert into category (category_name, category_desc) values ('Performance Arts', 'Direct community theater productions');
insert into category (category_name, category_desc) values ('Surplus Food Recovery', 'Collect excess food from restaurants');
insert into category (category_name, category_desc) values ('Policy Research', 'Research community issues for advocacy');
insert into category (category_name, category_desc) values ('Voter Registration', 'Register voters and provide education');
insert into category (category_name, category_desc) values ('Heritage Conservation', 'Restore historic buildings and landmarks');
insert into category (category_name, category_desc) values ('Youth Athletics', 'Coach children in sports and teamwork');
insert into category (category_name, category_desc) values ('Singing Group', 'Lead community choir practices');
insert into category (category_name, category_desc) values ('Science Education', 'Teach STEM through hands-on experiments');
insert into category (category_name, category_desc) values ('Cooperative Farming', 'Maintain community farm plots');
insert into category (category_name, category_desc) values ('Business Development', 'Mentor aspiring entrepreneurs');
insert into category (category_name, category_desc) values ('Prison Literacy', 'Teach reading and GED prep to inmates');
insert into category (category_name, category_desc) values ('Parenting Support', 'Guide parents through infant care');
insert into category (category_name, category_desc) values ('Mobile Library', 'Bring books to underserved neighborhoods');
insert into category (category_name, category_desc) values ('Youth Leadership', 'Train teens to lead service projects');
insert into category (category_name, category_desc) values ('Mural Creation', 'Paint public murals to beautify neighborhoods');
insert into category (category_name, category_desc) values ('Bike Maintenance', 'Repair bicycles for low-income commuters');
insert into category (category_name, category_desc) values ('Classical Music', 'Perform concerts for seniors');
insert into category (category_name, category_desc) values ('Dance Instruction', 'Teach dance styles for all ages');
insert into category (category_name, category_desc) values ('Yoga Outreach', 'Lead free yoga classes for stressed groups');
insert into category (category_name, category_desc) values ('Culinary Training', 'Teach cooking and nutrition');
insert into category (category_name, category_desc) values ('Photography Lessons', 'Teach photography to youth');
insert into category (category_name, category_desc) values ('Cinema Club', 'Screen documentaries on social issues');
insert into category (category_name, category_desc) values ('Reading Circle', 'Facilitate book club discussions');
insert into category (category_name, category_desc) values ('Acting Workshop', 'Teach drama to build confidence');
insert into category (category_name, category_desc) values ('Vocal Training', 'Teach singing techniques');
insert into category (category_name, category_desc) values ('Brass Ensemble', 'Lead community band rehearsals');
insert into category (category_name, category_desc) values ('Dance Performances', 'Choreograph cultural dance shows');
insert into category (category_name, category_desc) values ('Exhibition Space', 'Curate art exhibitions for local artists');
insert into category (category_name, category_desc) values ('Craft Workshops', 'Teach therapeutic handmade crafts');
insert into category (category_name, category_desc) values ('Garden Cooperative', 'Grow vegetables in shared plots');
insert into category (category_name, category_desc) values ('Running Groups', 'Lead community running clubs');
insert into category (category_name, category_desc) values ('Cycling Tours', 'Organize group bike rides');
insert into category (category_name, category_desc) values ('Nature Walks', 'Lead hiking groups');
insert into category (category_name, category_desc) values ('Bird Watching', 'Teach bird identification skills');
insert into category (category_name, category_desc) values ('Angling Programs', 'Teach fishing and water safety');
insert into category (category_name, category_desc) values ('Fiber Arts', 'Teach knitting for charity donations');
insert into category (category_name, category_desc) values ('Tailoring Classes', 'Teach sewing and clothing repair');
insert into category (category_name, category_desc) values ('Ceramics Studio', 'Teach pottery to beginners');
insert into category (category_name, category_desc) values ('Wood Craft', 'Teach safe woodworking skills');
insert into category (category_name, category_desc) values ('Strategy Games', 'Teach chess for critical thinking');
insert into category (category_name, category_desc) values ('Tabletop Gaming', 'Host board game nights');
insert into category (category_name, category_desc) values ('Esports Programs', 'Run gaming tournaments for teens');
insert into category (category_name, category_desc) values ('Card Games', 'Teach card games to seniors');
insert into category (category_name, category_desc) values ('Puzzle Solving', 'Host puzzle competitions');
insert into category (category_name, category_desc) values ('Paper Folding', 'Teach origami as meditative art');
insert into category (category_name, category_desc) values ('Memory Albums', 'Help seniors create scrapbooks');
insert into category (category_name, category_desc) values ('Beautiful Writing', 'Teach calligraphy as therapeutic art');
insert into category (category_name, category_desc) values ('Painting Classes', 'Teach painting techniques');
insert into category (category_name, category_desc) values ('Sketching Workshops', 'Teach drawing fundamentals');
insert into category (category_name, category_desc) values ('After-School Programs', 'Lead educational activities for youth');
insert into category (category_name, category_desc) values ('Elder Care', 'Assist seniors with daily tasks');
insert into category (category_name, category_desc) values ('Animal Adoption', 'Match pets with homes through adoption');
insert into category (category_name, category_desc) values ('Eco Conservation', 'Protect ecosystems through restoration');
insert into category (category_name, category_desc) values ('Street Outreach', 'Connect homeless to shelter services');
insert into category (category_name, category_desc) values ('Crisis Response', 'Coordinate volunteers for emergencies');