PRAGMA foreign_keys = ON;

create table category (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name VARCHAR(30),
    category_desc TEXT
);

insert into category (category_name, category_desc) values ('Elderly Companionship', 'Visit and provide social interaction to isolated seniors in homes or care facilities');
insert into category (category_name, category_desc) values ('Meal Delivery', 'Deliver hot meals to homebound elderly, disabled, or ill individuals');
insert into category (category_name, category_desc) values ('Pet Care Support', 'Help individuals care for pets through feeding, walking, or veterinary assistance');
insert into category (category_name, category_desc) values ('Park Restoration', 'Clean and maintain local parks through litter removal and planting activities');
insert into category (category_name, category_desc) values ('Shelter Assistance', 'Support homeless shelters by serving meals, organizing donations, or providing companionship');
insert into category (category_name, category_desc) values ('Emergency Relief', 'Assist communities during natural disasters through cleanup and supply distribution');
insert into category (category_name, category_desc) values ('Event Coordination', 'Plan and organize neighborhood gatherings and community celebrations');
insert into category (category_name, category_desc) values ('Wellness Checkups', 'Assist with health screening events and provide basic health education');
insert into category (category_name, category_desc) values ('Tutoring Services', 'Provide academic support to students in reading, math, or other subjects');
insert into category (category_name, category_desc) values ('Cultural Activities', 'Lead arts, crafts, or cultural workshops for underserved communities');
insert into category (category_name, category_desc) values ('Fitness Programs', 'Organize sports and recreational activities for underserved youth');
insert into category (category_name, category_desc) values ('Food Distribution', 'Sort, pack, and distribute food at food banks for families in need');
insert into category (category_name, category_desc) values ('Counseling Support', 'Provide emotional support and resource connections for mental health needs');
insert into category (category_name, category_desc) values ('Military Family Aid', 'Support veteran families with childcare, errands, or home maintenance');
insert into category (category_name, category_desc) values ('Leadership Workshops', 'Empower women through skill-building in leadership and entrepreneurship');
insert into category (category_name, category_desc) values ('Newcomer Services', 'Help refugees settle through language practice and resource navigation');
insert into category (category_name, category_desc) values ('24/7 Phone Support', 'Staff crisis hotlines to provide immediate support during emergencies');
insert into category (category_name, category_desc) values ('Reading Assistance', 'Teach basic literacy and reading skills to adults');
insert into category (category_name, category_desc) values ('Housing Navigation', 'Guide families through the process of finding affordable housing');
insert into category (category_name, category_desc) values ('Legal Consultation', 'Offer pro bono legal guidance on housing, immigration, or family law');
insert into category (category_name, category_desc) values ('Digital Skills', 'Teach computer basics and internet navigation to seniors and low-income individuals');
insert into category (category_name, category_desc) values ('Career Mentoring', 'Guide at-risk youth in career exploration and job readiness skills');
insert into category (category_name, category_desc) values ('Urban Gardening', 'Build community gardens providing fresh produce to food-insecure neighborhoods');
insert into category (category_name, category_desc) values ('Reentry Programs', 'Support formerly incarcerated individuals with job training and housing');
insert into category (category_name, category_desc) values ('Addiction Support', 'Facilitate recovery groups and connect individuals to treatment resources');
insert into category (category_name, category_desc) values ('Skills Training', 'Teach vocational skills like carpentry, coding, or culinary arts');
insert into category (category_name, category_desc) values ('Accessibility Support', 'Assist people with disabilities with daily tasks and transportation');
insert into category (category_name, category_desc) values ('Health Outreach', 'Distribute health information about vaccinations and preventive care');
insert into category (category_name, category_desc) values ('Rights Education', 'Teach community members about their civil and tenant rights');
insert into category (category_name, category_desc) values ('Language Exchange', 'Connect native speakers with newcomers for language practice and friendship');
insert into category (category_name, category_desc) values ('Senior Recreation', 'Lead activities, games, and exercise classes at senior centers');
insert into category (category_name, category_desc) values ('Safety Partnerships', 'Build trust between police and community through dialogue programs');
insert into category (category_name, category_desc) values ('Abuse Prevention', 'Educate about domestic violence warning signs and support resources');
insert into category (category_name, category_desc) values ('Immigration Help', 'Assist immigrants with paperwork, translation, and citizenship preparation');
insert into category (category_name, category_desc) values ('Animal Rescue', 'Care for injured or orphaned wildlife through rehabilitation');
insert into category (category_name, category_desc) values ('Healing Through Music', 'Lead therapeutic music sessions for hospital patients or hospice residents');
insert into category (category_name, category_desc) values ('Home Maintenance', 'Provide free home repairs and safety modifications for elderly homeowners');
insert into category (category_name, category_desc) values ('Transit Advocacy', 'Campaign for improved public transportation access in underserved areas');
insert into category (category_name, category_desc) values ('Neighborhood Cleanup', 'Remove litter and beautify streets, parks, and public spaces');
insert into category (category_name, category_desc) values ('Money Management', 'Teach budgeting, saving, and financial planning to low-income families');
insert into category (category_name, category_desc) values ('Teen Leadership', 'Develop leadership skills and civic engagement in young people');
insert into category (category_name, category_desc) values ('Creative Healing', 'Use art as therapeutic tool for trauma recovery and emotional expression');
insert into category (category_name, category_desc) values ('LGBTQ+ Outreach', 'Provide safe spaces, peer support, and advocacy for LGBTQ+ individuals');
insert into category (category_name, category_desc) values ('Media Production', 'Create community radio content highlighting local stories and issues');
insert into category (category_name, category_desc) values ('Solar Installation', 'Install solar panels for low-income homes to reduce utility costs');
insert into category (category_name, category_desc) values ('Performance Arts', 'Direct community theater productions showcasing local talent');
insert into category (category_name, category_desc) values ('Surplus Food Recovery', 'Collect excess food from restaurants to redistribute to families');
insert into category (category_name, category_desc) values ('Policy Research', 'Research community issues to inform advocacy and policy solutions');
insert into category (category_name, category_desc) values ('Voter Registration', 'Register community members and provide voter education');
insert into category (category_name, category_desc) values ('Heritage Conservation', 'Restore historic buildings and landmarks important to community identity');
insert into category (category_name, category_desc) values ('Youth Athletics', 'Coach underserved children in sports while teaching teamwork and discipline');
insert into category (category_name, category_desc) values ('Singing Group', 'Lead community choir practices and performances');
insert into category (category_name, category_desc) values ('Science Education', 'Teach STEM through hands-on experiments to underserved students');
insert into category (category_name, category_desc) values ('Cooperative Farming', 'Maintain community farm plots where neighbors grow produce together');
insert into category (category_name, category_desc) values ('Business Development', 'Help aspiring entrepreneurs start small businesses through mentoring');
insert into category (category_name, category_desc) values ('Prison Literacy', 'Teach reading and GED preparation to incarcerated individuals');
insert into category (category_name, category_desc) values ('Parenting Support', 'Guide first-time parents through infant care and child development');
insert into category (category_name, category_desc) values ('Mobile Library', 'Bring books and reading programs to underserved neighborhoods');
insert into category (category_name, category_desc) values ('Youth Leadership', 'Train teenagers to plan and lead community service projects');
insert into category (category_name, category_desc) values ('Mural Creation', 'Paint public murals collaboratively to beautify neighborhoods');
insert into category (category_name, category_desc) values ('Bike Maintenance', 'Repair bicycles for low-income commuters who depend on bikes');
insert into category (category_name, category_desc) values ('Classical Music', 'Perform free concerts for seniors in care facilities');
insert into category (category_name, category_desc) values ('Dance Instruction', 'Teach various dance styles to all ages as exercise and expression');
insert into category (category_name, category_desc) values ('Yoga Outreach', 'Lead free yoga classes for stressed populations like caregivers or veterans');
insert into category (category_name, category_desc) values ('Culinary Training', 'Teach cooking and nutrition to food-insecure families');
insert into category (category_name, category_desc) values ('Photography Lessons', 'Teach photography skills to youth as creative outlet');
insert into category (category_name, category_desc) values ('Cinema Club', 'Screen documentaries with discussions on social issues');
insert into category (category_name, category_desc) values ('Reading Circle', 'Facilitate book club discussions promoting literacy and connection');
insert into category (category_name, category_desc) values ('Acting Workshop', 'Teach drama to shy youth to build confidence');
insert into category (category_name, category_desc) values ('Vocal Training', 'Teach singing techniques through lessons and workshops');
insert into category (category_name, category_desc) values ('Brass Ensemble', 'Lead community band rehearsals and performances');
insert into category (category_name, category_desc) values ('Dance Performances', 'Choreograph community dance shows celebrating cultural traditions');
insert into category (category_name, category_desc) values ('Exhibition Space', 'Curate art exhibitions showcasing local artists');
insert into category (category_name, category_desc) values ('Craft Workshops', 'Teach handmade crafts as therapeutic and income-generating skills');
insert into category (category_name, category_desc) values ('Garden Cooperative', 'Grow vegetables collaboratively in shared community plots');
insert into category (category_name, category_desc) values ('Running Groups', 'Lead community running clubs and organize charity races');
insert into category (category_name, category_desc) values ('Cycling Tours', 'Organize group bike rides promoting eco-friendly transportation');
insert into category (category_name, category_desc) values ('Nature Walks', 'Lead hiking groups for fitness and nature appreciation');
insert into category (category_name, category_desc) values ('Bird Watching', 'Teach nature observation and bird identification skills');
insert into category (category_name, category_desc) values ('Angling Programs', 'Teach fishing and water safety to youth');
insert into category (category_name, category_desc) values ('Fiber Arts', 'Teach knitting to create items donated to shelters and hospitals');
insert into category (category_name, category_desc) values ('Tailoring Classes', 'Teach sewing and clothing repair for sustainability');
insert into category (category_name, category_desc) values ('Ceramics Studio', 'Teach pottery to beginners as creative expression');
insert into category (category_name, category_desc) values ('Wood Craft', 'Teach safe woodworking for building furniture and toys');
insert into category (category_name, category_desc) values ('Strategy Games', 'Teach chess to youth to develop critical thinking');
insert into category (category_name, category_desc) values ('Tabletop Gaming', 'Host board game nights for social connection');
insert into category (category_name, category_desc) values ('Esports Programs', 'Run gaming tournaments for teens to develop teamwork');
insert into category (category_name, category_desc) values ('Card Games', 'Teach card games to seniors for cognitive function');
insert into category (category_name, category_desc) values ('Puzzle Solving', 'Host puzzle competitions and collaborative events');
insert into category (category_name, category_desc) values ('Paper Folding', 'Teach origami as meditative art promoting focus');
insert into category (category_name, category_desc) values ('Memory Albums', 'Help seniors create scrapbooks documenting life stories');
insert into category (category_name, category_desc) values ('Beautiful Writing', 'Teach calligraphy as therapeutic art and marketable skill');
insert into category (category_name, category_desc) values ('Painting Classes', 'Teach painting techniques to all skill levels');
insert into category (category_name, category_desc) values ('Sketching Workshops', 'Teach drawing fundamentals including perspective and shading');
insert into category (category_name, category_desc) values ('After-School Programs', 'Supervise and lead educational activities for youth');
insert into category (category_name, category_desc) values ('Elder Care', 'Assist seniors with grocery shopping, housekeeping, and companionship');
insert into category (category_name, category_desc) values ('Animal Adoption', 'Match rescued pets with loving homes through adoption events');
insert into category (category_name, category_desc) values ('Eco Conservation', 'Protect local ecosystems through habitat restoration');
insert into category (category_name, category_desc) values ('Street Outreach', 'Connect homeless individuals to shelter and social services');
insert into category (category_name, category_desc) values ('Crisis Response', 'Respond to emergencies by coordinating volunteers and supplies');