PRAGMA foreign_keys = ON;

create table user (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT,
	role_id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50) UNIQUE,
	password TEXT,
	address VARCHAR(50),
	phone INT,
	is_active boolean,
	created_at DATE,
	FOREIGN KEY (role_id) REFERENCES userprofile(role_id)
);
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (1, 4, 'Latisha', 'Brandle', 'latisha.brandle@volunteer.com', 'password123', '831 Oak Valley Point', 91176571, true, '01/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (2, 2, 'Pennie', 'Burree', 'pennie.burree@volunteer.com', 'password123', '035 Gulseth Plaza', 87402034, false, '05/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (3, 4, 'Lionello', 'Pryde', 'lionello.pryde@volunteer.com', 'password123', '64536 Continental Center', 99548636, false, '02/06/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (4, 2, 'Ewan', 'McColgan', 'ewan.mccolgan@volunteer.com', 'password123', '3032 Buena Vista Plaza', 99648625, true, '17/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (5, 2, 'Carlos', 'Rushbrook', 'carlos.rushbrook@volunteer.com', 'password123', '38236 Graedel Parkway', 82040164, true, '21/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (6, 3, 'Kirsteni', 'Demcik', 'kirsteni.demcik@volunteer.com', 'password123', '33606 Hazelcrest Hill', 93393521, false, '15/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (7, 4, 'Vanda', 'Whitney', 'vanda.whitney@volunteer.com', 'password123', '84045 Heffernan Junction', 85638021, false, '09/06/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (8, 2, 'Alidia', 'Summerill', 'alidia.summerill@volunteer.com', 'password123', '64255 Northfield Pass', 94512134, false, '31/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (9, 3, 'Bambi', 'Berkely', 'bambi.berkely@volunteer.com', 'password123', '080 Crest Line Center', 83996206, true, '17/01/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (10, 3, 'Terrence', 'Quadrio', 'terrence.quadrio@volunteer.com', 'password123', '8 Michigan Way', 99990558, false, '24/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (11, 2, 'Eustace', 'Egalton', 'eustace.egalton@volunteer.com', 'password123', '6773 Mockingbird Pass', 87346441, false, '12/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (12, 4, 'Loreen', 'Tal', 'loreen.tal@volunteer.com', 'password123', '09 Coleman Pass', 80294508, false, '23/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (13, 1, 'Brander', 'Dobbins', 'brander.dobbins@volunteer.com', 'password123', '9 Ronald Regan Circle', 88364529, false, '28/10/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (14, 3, 'Grover', 'Hallede', 'grover.hallede@volunteer.com', 'password123', '91214 Sommers Lane', 92832039, true, '17/06/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (15, 2, 'Rhonda', 'Bonnet', 'rhonda.bonnet@volunteer.com', 'password123', '7519 Bayside Avenue', 94384423, true, '02/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (16, 2, 'Brenna', 'Winkless', 'brenna.winkless@volunteer.com', 'password123', '51 Park Meadow Pass', 84599978, false, '24/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (17, 2, 'Alvis', 'Flay', 'alvis.flay@volunteer.com', 'password123', '049 Eagle Crest Center', 91189414, true, '01/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (18, 3, 'Carrie', 'Nutty', 'carrie.nutty@volunteer.com', 'password123', '28 Aberg Street', 97618514, true, '15/01/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (19, 1, 'Hollyanne', 'Carp', 'hollyanne.carp@volunteer.com', 'password123', '3 Sachtjen Hill', 93358385, false, '16/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (20, 1, 'Lawton', 'Korfmann', 'lawton.korfmann@volunteer.com', 'password123', '1 Graceland Terrace', 87065771, true, '12/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (21, 3, 'Bethany', 'McIlharga', 'bethany.mcilharga@volunteer.com', 'password123', '9 Boyd Street', 98446147, false, '02/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (22, 4, 'Goldy', 'Hoble', 'goldy.hoble@volunteer.com', 'password123', '28 Mosinee Plaza', 85925452, false, '21/10/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (23, 2, 'Marie-ann', 'Wishkar', 'marie-ann.wishkar@volunteer.com', 'password123', '8 Tony Road', 95865123, false, '05/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (24, 1, 'Rosanna', 'Adanet', 'rosanna.adanet@volunteer.com', 'password123', '667 Fairview Court', 83016716, true, '19/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (25, 3, 'Mirna', 'Roset', 'mirna.roset@volunteer.com', 'password123', '3 Wayridge Circle', 85986447, false, '12/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (26, 3, 'Erinna', 'Atcherley', 'erinna.atcherley@volunteer.com', 'password123', '7 Chinook Point', 95473200, false, '02/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (27, 1, 'Ami', 'Slater', 'ami.slater@volunteer.com', 'password123', '291 Waywood Court', 94168999, true, '16/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (28, 2, 'Ariadne', 'Currum', 'ariadne.currum@volunteer.com', 'password123', '34205 Scofield Crossing', 99820527, false, '29/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (29, 2, 'Bren', 'Grasha', 'bren.grasha@volunteer.com', 'password123', '1575 Elmside Crossing', 95660862, true, '12/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (30, 2, 'Fanni', 'Whatham', 'fanni.whatham@volunteer.com', 'password123', '76329 Pond Center', 92647823, false, '05/10/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (31, 3, 'Jessee', 'Seabert', 'jessee.seabert@volunteer.com', 'password123', '854 Charing Cross Parkway', 94352971, false, '17/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (32, 3, 'Sofie', 'Rentcome', 'sofie.rentcome@volunteer.com', 'password123', '31160 Fair Oaks Drive', 96447541, true, '29/01/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (33, 1, 'Xenia', 'McPeice', 'xenia.mcpeice@volunteer.com', 'password123', '3 International Center', 82716152, false, '03/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (34, 3, 'Murry', 'Hotson', 'murry.hotson@volunteer.com', 'password123', '5390 Knutson Court', 82126996, false, '21/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (35, 3, 'Uri', 'Gettens', 'uri.gettens@volunteer.com', 'password123', '36215 Lakewood Road', 94375842, true, '28/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (36, 2, 'Florenza', 'Koenen', 'florenza.koenen@volunteer.com', 'password123', '63732 Lerdahl Hill', 91920766, true, '06/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (37, 3, 'Domenico', 'Waller-Bridge', 'domenico.waller-bridge@volunteer.com', 'password123', '82733 Sherman Court', 95002627, true, '31/10/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (38, 1, 'Fawn', 'Dameisele', 'fawn.dameisele@volunteer.com', 'password123', '1336 Merry Park', 81763550, true, '19/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (39, 3, 'Lexis', 'Montier', 'lexis.montier@volunteer.com', 'password123', '88977 Hauk Plaza', 91673954, true, '10/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (40, 1, 'Tyson', 'Rohan', 'tyson.rohan@volunteer.com', 'password123', '08 West Park', 96982252, false, '18/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (41, 2, 'Rosemarie', 'Crowcher', 'rosemarie.crowcher@volunteer.com', 'password123', '8167 Nova Circle', 81059708, true, '28/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (42, 1, 'Willy', 'Ludlamme', 'willy.ludlamme@volunteer.com', 'password123', '332 Pennsylvania Drive', 94390742, false, '30/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (43, 4, 'Hilliary', 'Bernardt', 'hilliary.bernardt@volunteer.com', 'password123', '0445 Shelley Way', 94003057, false, '02/06/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (44, 1, 'Gloriane', 'Bissatt', 'gloriane.bissatt@volunteer.com', 'password123', '54 Center Trail', 98837924, false, '25/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (45, 1, 'Hermina', 'Lutwidge', 'hermina.lutwidge@volunteer.com', 'password123', '43 Pond Point', 83653447, true, '22/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (46, 3, 'Cathi', 'Thebe', 'cathi.thebe@volunteer.com', 'password123', '4870 Goodland Terrace', 85030080, true, '06/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (47, 2, 'Sumner', 'Ronca', 'sumner.ronca@volunteer.com', 'password123', '6033 Golf View Road', 91766151, true, '13/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (48, 2, 'Errick', 'Fontenot', 'errick.fontenot@volunteer.com', 'password123', '10 Kipling Place', 85509742, true, '22/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (49, 1, 'Gerianna', 'Manon', 'gerianna.manon@volunteer.com', 'password123', '775 Northland Way', 86036137, true, '06/07/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (50, 1, 'Terese', 'Newsham', 'terese.newsham@volunteer.com', 'password123', '12972 Northridge Drive', 95371377, true, '23/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (51, 2, 'Merola', 'Andover', 'merola.andover@volunteer.com', 'password123', '83 6th Avenue', 82485902, true, '07/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (52, 1, 'Alli', 'Blanshard', 'alli.blanshard@volunteer.com', 'password123', '51 Sutherland Lane', 81787908, true, '24/04/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (53, 4, 'Erinna', 'Lendon', 'erinna.lendon@volunteer.com', 'password123', '6 Fair Oaks Way', 92333829, false, '15/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (54, 2, 'Emmalynne', 'Howsego', 'emmalynne.howsego@volunteer.com', 'password123', '98 Anderson Road', 99811662, true, '08/01/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (55, 4, 'Germana', 'Ouslem', 'germana.ouslem@volunteer.com', 'password123', '795 Magdeline Crossing', 81032263, true, '14/10/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (56, 4, 'Arleen', 'Rappoport', 'arleen.rappoport@volunteer.com', 'password123', '4342 Farragut Road', 86088506, false, '10/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (57, 4, 'Odette', 'Cuttings', 'odette.cuttings@volunteer.com', 'password123', '50 Tony Way', 90749677, true, '01/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (58, 3, 'Murial', 'Bayliss', 'murial.bayliss@volunteer.com', 'password123', '933 Burning Wood Court', 84252177, false, '24/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (59, 2, 'Weston', 'Seaking', 'weston.seaking@volunteer.com', 'password123', '5812 Pine View Plaza', 92154554, true, '30/10/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (60, 3, 'Bear', 'Macklam', 'bear.macklam@volunteer.com', 'password123', '1754 Maple Wood Street', 97626504, true, '31/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (61, 2, 'Dorey', 'Maciejewski', 'dorey.maciejewski@volunteer.com', 'password123', '64127 Warbler Alley', 99402682, true, '19/07/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (62, 4, 'Noe', 'Deave', 'noe.deave@volunteer.com', 'password123', '4 Loeprich Terrace', 86523989, true, '05/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (63, 1, 'Frederique', 'Cruise', 'frederique.cruise@volunteer.com', 'password123', '2638 Heath Place', 87014874, true, '13/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (64, 2, 'Jillayne', 'Bradfield', 'jillayne.bradfield@volunteer.com', 'password123', '31139 4th Pass', 84423679, false, '30/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (65, 1, 'Bill', 'Rayman', 'bill.rayman@volunteer.com', 'password123', '6 Karstens Circle', 98130256, true, '06/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (66, 3, 'Farlie', 'Schimmang', 'farlie.schimmang@volunteer.com', 'password123', '4091 Banding Park', 90574198, false, '01/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (67, 1, 'Rossie', 'Mustoe', 'rossie.mustoe@volunteer.com', 'password123', '85 Shelley Crossing', 97893957, false, '18/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (68, 2, 'Corinne', 'Fosse', 'corinne.fosse@volunteer.com', 'password123', '4 Bultman Terrace', 81884369, true, '24/01/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (69, 4, 'Dylan', 'Howieson', 'dylan.howieson@volunteer.com', 'password123', '9885 Forster Road', 86080605, false, '21/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (70, 2, 'Babara', 'Hazeldean', 'babara.hazeldean@volunteer.com', 'password123', '24 Nevada Road', 92963099, true, '12/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (71, 1, 'Raphael', 'Fanthome', 'raphael.fanthome@volunteer.com', 'password123', '83 Sheridan Street', 86557936, false, '26/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (72, 4, 'Bran', 'McElree', 'bran.mcelree@volunteer.com', 'password123', '8 Lighthouse Bay Trail', 94286186, false, '09/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (73, 2, 'Emile', 'Sargison', 'emile.sargison@volunteer.com', 'password123', '816 Blaine Crossing', 83364032, true, '14/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (74, 3, 'Torey', 'McGannon', 'torey.mcgannon@volunteer.com', 'password123', '19547 Miller Way', 96516689, false, '26/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (75, 2, 'Kaela', 'Corstorphine', 'kaela.corstorphine@volunteer.com', 'password123', '7 Sutherland Terrace', 96095308, true, '29/06/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (76, 2, 'Beverley', 'Nudde', 'beverley.nudde@volunteer.com', 'password123', '87028 Hoard Crossing', 97130472, false, '31/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (77, 1, 'Goldina', 'Turneaux', 'goldina.turneaux@volunteer.com', 'password123', '251 Browning Road', 86039929, false, '20/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (78, 4, 'Dacia', 'Tures', 'dacia.tures@volunteer.com', 'password123', '9269 Swallow Hill', 82209947, false, '03/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (79, 2, 'Grange', 'Harbach', 'grange.harbach@volunteer.com', 'password123', '1 Knutson Road', 93750543, false, '31/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (80, 2, 'Bianka', 'Ambroix', 'bianka.ambroix@volunteer.com', 'password123', '02984 Dayton Terrace', 91920335, false, '08/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (81, 3, 'Petronia', 'Kenwood', 'petronia.kenwood@volunteer.com', 'password123', '1 Dexter Place', 97366321, true, '06/07/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (82, 1, 'Florenza', 'Turfitt', 'florenza.turfitt@volunteer.com', 'password123', '71 Everett Way', 89172192, false, '16/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (83, 3, 'Barry', 'Fairnie', 'barry.fairnie@volunteer.com', 'password123', '4204 Eagan Avenue', 86705545, false, '02/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (84, 4, 'Scotti', 'Chomley', 'scotti.chomley@volunteer.com', 'password123', '30339 Lukken Road', 93565014, true, '23/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (85, 4, 'Kassandra', 'Godehard.sf', 'kassandra.godehard.sf@volunteer.com', 'password123', '03561 Banding Junction', 85017761, true, '13/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (86, 2, 'Delila', 'Parradine', 'delila.parradine@volunteer.com', 'password123', '97 Stone Corner Way', 99064622, true, '18/02/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (87, 2, 'Webb', 'Alebrooke', 'webb.alebrooke@volunteer.com', 'password123', '024 North Trail', 84630647, false, '21/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (88, 1, 'Julie', 'Jamary', 'julie.jamary@volunteer.com', 'password123', '12 Gulseth Place', 91331399, true, '22/03/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (89, 1, 'Milty', 'Spensley', 'milty.spensley@volunteer.com', 'password123', '0986 Eliot Lane', 95906040, true, '27/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (90, 3, 'Tansy', 'Farrer', 'tansy.farrer@volunteer.com', 'password123', '41 Jenifer Drive', 84376072, false, '07/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (91, 4, 'Ailsun', 'Shipston', 'ailsun.shipston@volunteer.com', 'password123', '399 Mockingbird Crossing', 93182293, false, '09/05/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (92, 4, 'Kylen', 'Foister', 'kylen.foister@volunteer.com', 'password123', '85 Kedzie Park', 92750556, true, '16/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (93, 3, 'Jermain', 'Bruggen', 'jermain.bruggen@volunteer.com', 'password123', '0 Bowman Court', 84395372, true, '05/07/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (94, 3, 'Dot', 'Nasey', 'dot.nasey@volunteer.com', 'password123', '50134 Waubesa Court', 92339353, false, '21/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (95, 4, 'Becca', 'Blampy', 'becca.blampy@volunteer.com', 'password123', '42 New Castle Avenue', 80311090, true, '28/09/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (96, 4, 'Mirabella', 'Setterfield', 'mirabella.setterfield@volunteer.com', 'password123', '79 Shelley Alley', 86079871, true, '29/01/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (97, 1, 'Marylin', 'Sayre', 'marylin.sayre@volunteer.com', 'password123', '28 Oriole Point', 80414481, true, '15/08/2025');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (98, 2, 'Marrissa', 'Gatley', 'marrissa.gatley@volunteer.com', 'password123', '13 Straubel Drive', 92683057, true, '22/12/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (99, 2, 'Sindee', 'Massen', 'sindee.massen@volunteer.com', 'password123', '4359 Fulton Place', 89585246, true, '09/11/2024');
insert into user (user_id, role_id, first_name, last_name, email, password, address, phone, is_active, created_at) values (100, 4, 'Marjy', 'Labrom', 'marjy.labrom@volunteer.com', 'password123', '12219 Forest Hill', 97798368, false, '05/02/2025');
